name: Build and deploy app to ec2 instance
on:
    push:
        branches:
            - main
jobs:
    Build_and_push_docker_image:
        runs-on: [local]
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3        
            
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                  vnavalianyi/jscc
                tags: |
                  type=sha
            
            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: app/.
                push: true
                tags: |
                  vnavalianyi/jscc:latest
                  ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    Create_infrastructure_aws:
      runs-on: [local]
      needs: Build_and_push_docker_image
      steps:
          - name: Check out the repo
            uses: actions/checkout@v3

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-central-1

          - name: Terraform init & plan
            env:
              TF_VAR_VPC_CIDR: ${{ secrets.TF_VAR_VPC_CIDR }}
              TF_VAR_SUB_CIDR: ${{ secrets.TF_VAR_SUB_CIDR }}
              TF_VAR_AVAIL_ZONE: ${{ secrets.TF_VAR_AVAIL_ZONE }}
              TF_VAR_ENV_PREFIX: ${{ secrets.TF_VAR_ENV_PREFIX }}
              TF_VAR_MY_IP: ${{ secrets.TF_VAR_MY_IP }}
              TF_VAR_INSTANCE_TYPE: ${{ secrets.TF_VAR_INSTANCE_TYPE }}
              TF_VAR_KEY_NAME: ${{ secrets.TF_VAR_KEY_NAME }}
              TF_VAR_IMAGE_NAME: ${{ secrets.TF_VAR_IMAGE_NAME }}
              TF_VAR_AMI_OWNER: ${{ secrets.TF_VAR_AMI_OWNER }}
              TF_VAR_REGION: ${{ secrets.TF_VAR_REGION }}
            run: |
              cd Terraform 
              terraform init 
              terraform plan
