name: Build and deploy app to ec2 instance
on:
    push:
        branches:
            - main
jobs:
    check_code:
        runs-on: [local]
        steps:
            - name: Print hello
              run: echo "first run on local worker"          
            
            - name: Print OS version
              run: uname -a