name: Build and deploy app to ec2 instance
on:
    push:
        branches:
            - main

env:
  IMAGE_NAME: vnavalianyi/jscc
  AWS_REGION: eu-central-1
            
jobs:
    # Build_and_push_docker_image:
    #     runs-on: [local]
    #     steps:
    #         - name: Check out the repo
    #           uses: actions/checkout@v3        
            
    #         - name: Docker meta
    #           id: meta
    #           uses: docker/metadata-action@v4
    #           with:
    #             images: ${{ env.IMAGE_NAME }}
    #             tags: |
    #               type=sha
            
    #         - name: Log in to Docker Hub
    #           uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
    #           with:
    #             username: ${{ secrets.DOCKER_USERNAME }}
    #             password: ${{ secrets.DOCKER_PASSWORD }}

    #         - name: Build and push
    #           uses: docker/build-push-action@v4
    #           with:
    #             context: app/.
    #             push: true
    #             tags: |
    #               ${{ env.IMAGE_NAME }}:latest
    #               ${{ steps.meta.outputs.tags }}
    #             labels: ${{ steps.meta.outputs.labels }}

    Create_infrastructure_aws:
      runs-on: [local]
      # needs: Build_and_push_docker_image
      steps:
          - name: Check out the repo
            uses: actions/checkout@v3

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Terraform init & plan
            env:
              TFVARS_FILE: ${{ secrets.TFVARS_FILE }}
            run: |
              cd Terraform 
              echo "$TFVARS_FILE" > terraform.tfvars
              terraform init
              terraform validate
              terraform plan
              terraform apply -auto-approve
            #  terraform output -raw ec2_public_ip > ip.txt

          - name: Save Terraform Outputs
            id: save-output
            run: |
                echo "ip=$(terraform output -raw ec2_public_ip)" >> "$GITHUB_ENV"

          - name: Save Terraform Outputs
            id: print-output
            run: |
                echo ${{ steps.save-output.outputs.ip }}


    # Run_image:
    #   runs-on: [local]
    #   needs: Create_infrastructure_aws
    #   steps:
    #       - name: Login to server
    #         run: 