name: Build and deploy app to ec2 instance
on:
    push:
        branches:
            - main
jobs:
    Build_docker_image:
        runs-on: [local]
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3        
            
            # - name: Build docker image
            #   run: docker build -t vnavalianyi/jscc:v1 -f app/Dockerfile app/.

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                  vnavalianyi/jscc
                # generate Docker tags based on the following events/attributes
                tags: |
                  type=semver,pattern={{major}}.{{minor}}
                  type=sha
            
            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: app/.
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}